name: Minecraft Server

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy lúc 0h (UTC)
    - cron: '0 3 * * *'  # Chạy lúc 3h (UTC)
    - cron: '0 6 * * *'  # Chạy lúc 6h (UTC)
    - cron: '0 9 * * *'  # Chạy lúc 9h (UTC)
    - cron: '0 12 * * *' # Chạy lúc 12h (UTC)
    - cron: '0 15 * * *' # Chạy lúc 15h (UTC)
    - cron: '0 18 * * *' # Chạy lúc 18h (UTC)
    - cron: '0 21 * * *' # Chạy lúc 21h (UTC)
  workflow_dispatch:  # Cho phép trigger thủ công từ GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest  # Sử dụng Ubuntu làm môi trường chạy server

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Lấy mã nguồn của repository

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Cài đặt Java 17
        distribution: 'temurin'  # Chỉ định phân phối Java là Temurin (hoặc bạn có thể dùng 'adoptopenjdk')

    - name: Start Minecraft Server
      run: |
        cd minecraft_server
        java -Xmx2G -Xms2G -jar minecraft_server.jar nogui # Khởi động server với 2GB RAM (có thể thay đổi tham số)
      continue-on-error: true

    - name: Wait for server to start
      run: |
        sleep 21600  # Đợi server Minecraft khởi động (có thể thay đổi thời gian)
